#spring.application.name=springboot
server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none #chỗ này mà sửa thành drop-create thì rất nguy
        #ddl-auto: validate
        #Hibernate sẽ không tạo, sửa đổi hoặc xóa bất kỳ bảng, cột hay ràng buộc nào trong cơ sở dữ liệu
        #validate thường được sử dụng trong môi trường production
        #Nếu có sự khác biệt giữa cấu trúc cơ sở dữ liệu và các entity class
        #lỗi sẽ được hiển thị và yêu cầu sửa đổi cấu trúc cơ sở dữ liệu một cách thủ công
      properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1